//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLAM4_EF_ECOLECONDUITE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEHICULE()
        {
            this.lesLecons = new HashSet<LECON>();
        }
    
        public string numImma { get; set; }
        public string modele { get; set; }
        public Nullable<int> cylindree { get; set; }
        public Nullable<bool> voitureO_N { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LECON> lesLecons { get; set; }
    }
}
